---
- name: Build all FPF containers.
  hosts: localhost
  connection: local
  gather_facts: no
  vars_prompt:
    - name: container_to_build
      prompt: "Container name to build: "
      private: no
      default: all
  tasks:
    - name: Find all container configs.
      find:
        paths:
          - "{{ playbook_dir }}"
        file_type: directory
      register: find_container_config_results

    - name: If user hit enter, build all containers
      set_fact:
        container_names: "{{ find_container_config_results.files|map(attribute='path')|map('basename')|list }}"
      when: "container_to_build == 'all'"

    - name: Set container names to user provided
      set_fact:
        container_names: ['{{ container_to_build }}']
      when: "container_to_build != 'all'"

    # Import separate task list to take advantage of `which_items` loop.
    - include: build-image.yml
      with_items: "{{ container_names }}"
