---
- name: Build all FPF containers.
  hosts: localhost
  connection: local
  gather_facts: no
  vars_prompt:
    - name: container_to_build
      prompt: "Container name to build: "
      private: no
      default: all
  tasks:
    - name: Find all container configs.
      find:
        paths:
          - "{{ playbook_dir }}"
        file_type: directory
      register: find_container_config_results

    - debug: var=find_container_config_results

    - name: Set container name list as fact.
      set_fact:
        container_names: "{{ find_container_config_results.files|map(attribute='path')|map('basename')|list }}"

    - debug: var=container_names

    # Import separate task list to take advantage of `which_items` loop.
    - include: build-image.yml
      with_items: "{{ container_names }}"
