---
reuse-blerbs:
  - &python_prereqs
    run:
      name: Install testing pre-reqs
      command: |
        # Set python to 3.5.2
        pyenv global 3.5.2
        pip install -U pip
        pip install pipenv
        pipenv install

version: 2
jobs:
  pytest:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout

      - *python_prereqs

      - run:
          name: Run pytest
          command: |
            mkdir -p tests || true
            pipenv run pytest --junit-xml=./tests/pytests.xml

      - store_test_results:
          path: tests

workflows:
  version: 2
  container_ci:
    jobs:
      - pytest
